name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: arthurlt
          password: ${{ secrets.CR_PAT }}
        uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag custom-caddy:$(date +%s)
      - name: Push the Docker image
        run: docker push ghcr.io/arthurlt/custom-caddy:$(date +%s)
