name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to GH Container Registry
      run: echo $CR_PAT | docker login ghcr.io -u arthurlt --password-stdin
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag custom-caddy:$(date +%s)
    - name: Push the Docker image
      run: docker push ghcr.io/arthurlt/custom-caddy:$(date +%s)
